spring:
  application:
    name: app
  datasource:
    url: jdbc:postgresql://localhost:5432/playground
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: '6Kyr0b1SQgePbkAHQbW45InZ14xIlWQG'
  expiration: 3600000